# Generated by Django 6.0.2 on 2026-03-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_habits_profile_initial_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapyplan',
            old_name='plan_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='therapyplan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='therapyplan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='therapyplan',
            name='user',
        ),
        migrations.AddField(
            model_name='therapyplan',
            name='category',
            field=models.CharField(default='metabolic', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapyplan',
            name='diet_plan',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapyplan',
            name='duration_days',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapyplan',
            name='herbs_plan',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapyplan',
            name='lifestyle_plan',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
