# Generated by Django 6.0.2 on 2026-03-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_plan_name_therapyplan_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='therapyplan',
            table='therapy_therapyplan',
        ),
    ]
